### PR TITLE
Add new routes

### PR DESCRIPTION
**Pull request by mrocklin**
This adds

-  Cluster Map
-  Compute time by operation
-  Compute / Transfer / Deserialization time
-  GPU plots

### CODE REVIEW

**Comment by mrocklin** [comment]
Yes.  In a related PR in dask/distributed I've made these plots robust to not having a GPU around.  They just return that there is no GPU activity.

**Comment by mrocklin** [comment]
https://github.com/dask/distributed/pull/4008

**Comment by mrocklin** [comment]
Hrm, does anyone have experience with the travis-ci failure?  It looks like maybe Miniconda's startup requirements changed since tests were last run?

**Comment by jacobtomlinson** [comment]
I've unblocked the CI here but uncovered further problems. Raised #140 to track them outside of this PR.

**Comment by mrocklin** [comment]
Thanks Jacob

**Pull request merged**
