### PR TITLE
Replace internal fork of nbserverproxy with jupyter-server-proxy

### PR DESCRIPTION
**Pull request by yuvipanda**

### CODE REVIEW

**Comment by yuvipanda** [comment]
The idea is that when a new cluster gets created, we register a new tornado handler returned by make_dashboard_handler. We can unregister it when cluster is deleted. This also lets us use cluster names rather than IDs if needed, and remove state that is matching cluster IDs with clusters.

**Comment by yuvipanda** [comment]
@ian-r-rose I also haven't actually tested this :D But it should work, and I copy pasted this code from another project I just did...

**Comment by ian-r-rose** [comment]
One thing I was at least trying to leave the door open to was dashboard servers that were running other places than `localhost`. I'm not aware of anywhere that this was actually done, but it seemed like it was a possibility for some remote cluster setups. Does this `LocalProxyHandler` approach remove that possibility?

**Comment by yuvipanda** [comment]
Nope it should be fine. We can make that configurable as the next step.

**Comment by mrocklin** [comment]
FYI @quasiben .  Nothing for you to do here, but wanted to make you aware
of the jupyter-server-proxy and how it's used in dask-labextension.

**Comment by quasiben** [comment]
👍

**Comment by ian-r-rose** [comment]
Fixes #49. cc @jakirkham

**Comment by dhirschfeld** [comment]
NB: My current distributed setup has a remote scheduler/dashboard. I am in the process of moving to k8s though but IIUC there are plans to allows remote schedulers there too

**Comment by ian-r-rose** [comment]
Thanks for the info @dhirschfeld. @yuvipanda, sounds like we should move remote-server proxying towards the front-burner.

**Comment by dhirschfeld** [comment]
No need to rush on my account - it's just something to keep in mind.

***xref:*** https://github.com/dask/dask-kubernetes/issues/84

**Comment by ian-r-rose** [comment]
Okay, this should be good to go from my end.

@dhirschfeld I think this should continue working with your remote dashboard setup, but let us know if there are any troubles.

**Comment by ian-r-rose** [comment]
Moving forwards with this. Thanks @yuvipanda!

**Comment by jakirkham** [comment]
Thanks so much all for working on this! 😄

**Pull request merged**
