### PR TITLE
Usability Fixes

### PR DESCRIPTION
**Pull request by ian-r-rose**
Fixes https://github.com/dask/dask-labextension/issues/21#issuecomment-418014155
Fixes https://github.com/dask/dask-labextension/issues/21#issuecomment-418014155

This should be published as a patch-release.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
I gave this branch a go and I think it fixed the incorrect naming but I'm still getting CORS errors so will give `nbserverproxy` a go...

**Comment by ian-r-rose** [comment]
Yes, I didn't attempt to fix any CORS issues with this PR. You *may* be able to disable CORS policies on a per-site basis for testing purposes, but that is probably not a good long-term solution.

**Comment by ian-r-rose** [comment]
It's looking like we should set up some best-practices around proxying the dashboard URL to be within the notebook server origin sooner rather than later. Do you know who has relevant experience doing that?

**Comment by mrocklin** [comment]
The Pangeo community is probably the best bet.  Typically we've just
install nbserverproxy in our docker images and then used that.  This hasn't
been particularly sophisticated so far.

**Comment by ian-r-rose** [comment]
Published as 0.1.1

**Comment by mrocklin** [comment]
Thanks @ian-r-rose

**Pull request merged**
