### PR TITLE
Update pins for bokeh and jupyter-server-proxy

### LINKED ISSUE #121: Update to use Bokeh >=2
It appears that the most recent release of bokeh(v2.0.0) included some breaking changes. As a result, the websocket connection is not being established properly:

Screen Shot 2020-03-19 at 1 55 28 PM
Screen Shot 2020-03-19 at 1 54 51 PM

I am running:

```
# Name                    Version                   Build  Channel
dask                      2.12.0                     py_0    conda-forge
dask-core                 2.12.0                     py_0    conda-forge
dask-labextension         2.0.0                      py_0    conda-forge
bokeh                     2.0.0            py37hc8dfbb8_0    conda-forge
```

```
$ jupyter labextension list
JupyterLab v2.0.1
Known labextensions:
   app dir: /glade/work/abanihi/softwares/miniconda3/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/toc v3.0.0  enabled  OK
        @pyviz/jupyterlab_pyviz v0.9.0  enabled  OK
        dask-labextension v2.0.0  enabled  OK
        jupyterlab-nvdashboard v0.1.9  enabled   X

   The following extension are outdated:
        jupyterlab-nvdashboard

   Consider running "jupyter labextension update --all" to check for updates.
```

### PR DESCRIPTION
**Pull request by jsignell**
Closes #121

### CODE REVIEW

**Comment by jsignell** [comment]
@jcrist - not sure who would be willing to ok this.

**Comment by ian-r-rose** [comment]
Looks good to me.

**Comment by ian-r-rose** [comment]
Thanks @jsignell

**Comment by michaelaye** [comment]
is there a pre-release available on pypi yet? I just had the pypi install remove by 2.0 bokeh still...

**Comment by jsignell** [comment]
Good point! @ian-r-rose do you mind kicking off a release? Let me know if you'd rather I do it.

**Comment by ian-r-rose** [comment]
I'm a little tied up today. Feel free to publish a point release if you have the time @jsignell, otherwise I can revisit in a day or two.

**Comment by TomAugspurger** [comment]
@ian-r-rose just confirming, are you comfortable with giving @jsignell write access to this repo so that she can push a tag?

**Comment by jsignell** [comment]
Ok I just pushed a tag as described in the README.

**Comment by ian-r-rose** [comment]
Sorry for the late reply, yes, happy to have @jsignell help out here! I actually don't have permissions to add collaborators, it seems 😄 

Thanks for the publish @jsignell

**Pull request merged**
