### PR TITLE
Updates for JupyterLab v0.35.

### PR DESCRIPTION
**Pull request by ian-r-rose**

### CODE REVIEW

**Comment by mrocklin** [comment]
It looks like your yarn.lock file was committed by mistake

**Comment by mrocklin** [comment]
Generally I'm *very* glad to see that this is being taken along and shifting with JLab.  Thank you @ian-r-rose for tracking this.

**Comment by ian-r-rose** [comment]
The yarn.lock was deliberate. Apparently that is considered best practices:
https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

**Comment by blink1073** [comment]
Ha, I was about to type what Ian just did ;).

**Pull request merged**
