### PR TITLE
Fix installation instructions.

### LINKED ISSUE #40: Refresh install instructions in README ?
The instructions installation provided in the README.md fails:

# The instructions that fail
#### Requirements
JupyterLab >= 0.35 distributed >= 1.24.1

#### Installation
This extension includes both a client-side JupyterLab extension and a server-side Jupyter notebook extension. Install these using the command line with

```
jupyter labextension install dask-labextension
jupyter serverextension install dask_labextension
```

# The failure

```sh
$ jupyter serverextension install dask_labextension
Please supply at least one subcommand: disable, enable, list
```

### PR DESCRIPTION
**Pull request by ian-r-rose**
Fixes #40. Thanks for pointing out the error @consideRatio

### CODE REVIEW

**Comment by consideRatio** [comment]
Thanks! I bet this will do it. 

Should perhaps the following line also be corrected?

```
# currently is sais this in the README:
jupyter serverextension enable --sys-prefix dask_labextension

# but without ability to test right now, I'm still thinking it should be like this:
jupyter serverextension enable --sys-prefix --py dask_labextension
```

**Comment by consideRatio** [comment]
I'm confused, on PYPI there is https://pypi.org/project/dask-labextension/

`dask-labextension` and `dask_labextension` both work. I assume there is an alias of some kind setup?

**Comment by consideRatio** [comment]
Yes I think you are right!

Things progressed and #40 was fixed, and the additional `--py` was indeed required for me to enable the serverextension manually system wide. Thanks for helping me get past this!

**Comment by ian-r-rose** [comment]
@consideRatio interesting, I have not needed to add the `--py` flag. Indeed, it's not clear to me what that flag is for at all, since I thought that all serverextensions were python. Do you have an understanding of it?

**Comment by consideRatio** [comment]
Thanks for your work on this extension and your help to figure this out @ian-r-rose!

The extension was utilized by a colleague of mine today :D (i have a jupyterhub for my colleagues in a datascience team)

**Pull request merged**
