### PR TITLE
Add explanatory screencast to README

### PR DESCRIPTION
**Pull request by mrocklin**

### CODE REVIEW

**Comment by mrocklin** [comment]
Hrm, it looks like GitHub prefers not to render raw HTML in readme markdown files (which seems reasonable enough).

Does anyone know of a workaround?  If not then I'll just include a link.

**Comment by ian-r-rose** [comment]
If memory serves, it will do some HTML, but sanitizes it pretty thoroughly.

[This](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#youtube-videos) shows how to make a decent youtube link with a preview.

**Comment by ian-r-rose** [comment]
Cool video, BTW :)

**Comment by mrocklin** [comment]
Thanks!  I've been spending a lot of this week screencasting, and someone asked for this one in particular in the comments of another video.

**Comment by mrocklin** [comment]
Is there a video that you would like included as a link in the end?  I've included the Dask dashboard walkthrough, but there is plenty of space for another one if you think that there is a good, short, JupyterLab video.

**Comment by ian-r-rose** [comment]
I think it's okay with this for the moment. Thanks!

**Pull request merged**
