### PR TITLE
Canavandl/individual routes

### PR DESCRIPTION
**Pull request by canavandl**
plot elements currently resize properly

### CODE REVIEW

**Comment by canavandl** [comment]
todo (potentially in another PR):
* the Bokeh elements could use some padding inside the Phosphor containers, but simply adding css padding/margin interfered with the resizing
* a nicer menu
* better handling of selecting an already active plot from the command palette (currently it moves the plot to the 'main' area). It's not currently horrible, but could be better.

**Comment by mrocklin** [comment]
@canavandl can we merge this?  I recommend that you take charge on pressing the green button on most of these things.

**Comment by canavandl** [comment]
I think I need to make some changes to the distributed branch and get that merged first. Then this will be able to work with master and/or a distributed release.

**Comment by canavandl** [comment]
The Bokeh team also resolved a memory leak in master that was causing issues with this extension: https://github.com/bokeh/bokeh/pull/5261

**Comment by canavandl** [comment]
Will have to update this PR to add placeholder argument when https://github.com/bokeh/bokeh/pull/5295 is merged

**Comment by canavandl** [comment]
superceded by #7

**Pull request closed without merging**
