### PR TITLE
Update for JL 1.0.0a6

### PR DESCRIPTION
**Pull request by athornton**
Make it build against JL 1.0.0a6.

Probably no sense in landing this until JL 1.0 is released.

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Thanks @athornton. I'm happy to merge this, though I accidentally just introduced a merge conflict in `yarn.lock`.

**Comment by athornton** [comment]
Oh, just regenerate it and commit.  I think I only deleted it because I wanted to make sure I was OK pulling current dependencies.

**Comment by ian-r-rose** [comment]
You're doing yeoman's work here, @athornton.

**Comment by athornton** [comment]
This last bit bumps everything to release version and resolves the merge conflicts.

**Comment by ian-r-rose** [comment]
Superseded by https://github.com/dask/dask-labextension/commit/9390022b36ffa0b953c6dc4414a0d29942bbaae6 , thanks for keeping this up-to-date @athornton. Should be able to install from PyPI/npm now.

**Pull request closed without merging**
